"""
enrich_products.py
------------------
Step 2 of 2. Uses an LLM to add the columns the team asked for:
Category, Product Type, Best For, Org Size, Keywords, Summary, Features.

Alternatives are NOT generated by the LLM (it would invent products
mon.co.th does not sell). They are computed in pass 2 from products that
actually exist in the catalog.

Input : products_base.csv   (from build_dataset.py)
Output: products_enriched.csv
Cache : enrich_cache.jsonl  -- safe to Ctrl+C and re-run, it resumes

CHANGE ONE LINE TO SWITCH ENGINE:
    BACKEND = "ollama"     free, runs locally, weakest Thai
    BACKEND = "openai"     ~12 THB for all 720, best value
    BACKEND = "anthropic"  ~40 THB for all 720, best Thai quality

For openai / anthropic put the key in a .env file (already gitignored):
    OPENAI_API_KEY=sk-...
    ANTHROPIC_API_KEY=sk-ant-...

Run:  python enrich_products.py
"""

import json
import os
import re
import sys
from pathlib import Path

import pandas as pd

# =====================================================================
BACKEND = "openai"          # <-- ollama | openai | anthropic
OLLAMA_MODEL = "qwen2.5:7b"  # 3b is too weak for Thai; 7b if RAM allows
OPENAI_MODEL = "gpt-4o-mini"
ANTHROPIC_MODEL = "claude-sonnet-4-6"
MAX_DESC_CHARS = 3000        # truncate giant descriptions to control cost
LIMIT = 0                    # 5 = test run. Set to 0 to process all 720.
# =====================================================================

SRC = "products_base.csv"
OUT = "products_enriched.csv"
CACHE = Path("enrich_cache.jsonl")


# ---------------------------------------------------------------
# Prompt
# ---------------------------------------------------------------
PRODUCT_TYPES = [
    "SIEM", "Log Management", "Antivirus", "EDR / XDR", "Firewall",
    "Web Application Firewall", "VPN", "Email Security", "Data Loss Prevention",
    "Backup & Recovery", "Cloud Storage", "Virtual Machine", "Cloud Hosting",
    "CDN", "DNS Security", "Identity & Access Management",
    "Multi-Factor Authentication", "Network Monitoring", "IT Service Management",
    "Productivity Suite", "Collaboration & Meeting", "Remote Access",
    "Document Management", "Design Software", "Operating System", "Database",
    "CRM", "Security Awareness Training", "Penetration Testing Service",
    "Managed Security Service", "Threat Intelligence", "Mobile Device Management",
    "Server Hardware", "Network Hardware", "Storage Hardware", "Other Software",
]

SYSTEM_PROMPT = f"""You are a data engineer building a product catalog for an IT
solutions company in Thailand (mon.co.th). Their customers are Thai businesses
and government agencies who search in BOTH Thai and English.

Given one product, return structured metadata for semantic search.

## LANGUAGE RULES (violating these makes the output unusable)
- Use ONLY Thai script and English/Latin letters.
- NEVER output Chinese, Japanese or Korean characters. Words like 統合, 管理,
  安全 are FORBIDDEN. Write "integration", "management", "security" instead.
- Always put a SPACE between a Thai word and an English word.
  Correct: "SIEM บน Cloud"   Wrong: "SIEMบนCloud"
- Translate these terms exactly. Do not invent alternatives:
    compliance      -> "สอดคล้องตามข้อกำหนด"  (NEVER "ความยุติธรรม")
    log             -> "ล็อก" or keep "Log"
    endpoint        -> "อุปกรณ์ปลายทาง"
    threat          -> "ภัยคุกคาม"
    backup          -> "สำรองข้อมูล"
    data loss       -> "ข้อมูลรั่วไหล"

## product_type
Pick EXACTLY ONE label from this list, copied character for character:
{", ".join(PRODUCT_TYPES)}
If nothing fits, use "Other Software". Never invent a new label.

## best_for and org_size
Do NOT default everything to Enterprise. Decide using PRICE FIRST, then the
tier number in the product name (1 < 2 < 3, Standard < Pro < Premium),
then user/device counts mentioned in the description.

Price bands (Thai Baht, use Price_Min for products with a range):
    under 3,000        -> ["Personal", "Small Office"]
    3,000 - 15,000     -> ["Small Business", "SME"]
    15,000 - 60,000    -> ["SME", "Enterprise"]
    over 60,000        -> ["Enterprise", "Government"]

Adjust only if the description clearly contradicts the price band.
Add "Government" ONLY when the description actually mentions Thai government
requirements such as พ.ร.บ. คอมพิวเตอร์, ICT, ระเบียบราชการ or งบราชการ.
Within one product family the tiers MUST differ from each other.

## category and keywords
- category = TECHNICAL DOMAIN ("SIEM", "Endpoint Security"), never a retail
  shelf path like "Electronics > Networking".
- keywords must cover what a customer would actually type, including
  abbreviations and common misspellings. Give at least 8 English and
  at least 6 Thai keywords.
- If information is not in the description, return an empty list. NEVER invent
  specifications, prices, certifications or compliance claims.

Output ONLY a JSON object. No markdown fences, no explanation.
{{
  "category": ["primary domain", "secondary domain"],
  "product_type": "one label copied from the list above",
  "best_for": ["..."],
  "org_size": ["..."],
  "keywords_en": ["...", "..."],
  "keywords_th": ["...", "..."],
  "summary_en": "1-2 sentences, max 40 words",
  "summary_th": "1-2 ประโยค ไม่เกิน 40 คำ",
  "features": ["...", "..."]
}}"""


def build_user_prompt(row):
    desc = str(row.get("Description") or "")[:MAX_DESC_CHARS]
    return f"""Product Name: {row['Title']}
Vendor: {row.get('Vendor') or 'unknown'}
Existing Type (may be wrong): {row.get('Type_Original') or 'none'}
Existing Category (likely wrong, ignore if it is a retail category): {row.get('Category_Original') or 'none'}
Shop Tags: {row.get('Tags') or 'none'}
Price: {row.get('Price_Display')}
Price_Min (use this for the org size band): {row.get('Price_Min') or 'unknown'}
Deployment detected: {row.get('Deployment') or 'unknown'}

Description:
{desc}"""


# ---------------------------------------------------------------
# Backends
# ---------------------------------------------------------------
def load_env():
    env = Path(".env")
    if env.exists():
        for line in env.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                os.environ.setdefault(k.strip(), v.strip())


def call_ollama(system, user):
    import ollama
    r = ollama.chat(
        model=OLLAMA_MODEL,
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        format="json",
        options={"temperature": 0.1},
    )
    return r["message"]["content"]


def call_openai(system, user):
    from openai import OpenAI
    client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])
    r = client.chat.completions.create(
        model=OPENAI_MODEL,
        temperature=0.1,
        response_format={"type": "json_object"},
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
    )
    return r.choices[0].message.content


def call_anthropic(system, user):
    import anthropic
    client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
    r = client.messages.create(
        model=ANTHROPIC_MODEL,
        max_tokens=1200,
        temperature=0.1,
        system=system,
        messages=[{"role": "user", "content": user}],
    )
    return r.content[0].text


BACKENDS = {"ollama": call_ollama, "openai": call_openai, "anthropic": call_anthropic}


def parse_json(text):
    text = re.sub(r"^\s*```(?:json)?|```\s*$", "", text.strip())
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        m = re.search(r"\{.*\}", text, re.S)
        if m:
            return json.loads(m.group(0))
        raise


CJK = re.compile(r"[\u3040-\u30ff\u3400-\u4dbf\u4e00-\u9fff\uac00-\ud7af]")
THAI_LATIN = re.compile(r"([\u0e00-\u0e7f])([A-Za-z0-9])")
LATIN_THAI = re.compile(r"([A-Za-z0-9])([\u0e00-\u0e7f])")


def has_cjk(data):
    """qwen sometimes leaks Chinese/Japanese characters into Thai text."""
    return bool(CJK.search(json.dumps(data, ensure_ascii=False)))


def fix_spacing(text):
    """Insert the missing space between Thai and Latin runs."""
    text = THAI_LATIN.sub(r"\1 \2", text)
    text = LATIN_THAI.sub(r"\1 \2", text)
    return re.sub(r" {2,}", " ", text).strip()


def snap_product_type(value):
    """Force the label onto the controlled vocabulary."""
    v = str(value or "").strip()
    if v in PRODUCT_TYPES:
        return v
    low = v.lower()
    for label in PRODUCT_TYPES:
        if low == label.lower():
            return label
    for label in PRODUCT_TYPES:
        if label.lower() in low or low in label.lower():
            return label
    return "Other Software"


def as_list(v):
    if isinstance(v, list):
        return [str(x).strip() for x in v if str(x).strip()]
    if v is None or (isinstance(v, float) and pd.isna(v)):
        return []
    return [s.strip() for s in str(v).split(",") if s.strip()]


# ---------------------------------------------------------------
# Pass 1 -- LLM enrichment, resumable
# ---------------------------------------------------------------
def enrich(df):
    done = {}
    if CACHE.exists():
        for line in CACHE.read_text(encoding="utf-8").splitlines():
            if line.strip():
                rec = json.loads(line)
                done[rec["Handle"]] = rec
        print(f"Resuming: {len(done)} products already cached")

    call = BACKENDS[BACKEND]
    todo = [r for _, r in df.iterrows() if r["Handle"] not in done]

    if LIMIT and LIMIT > 0:
        todo = todo[:LIMIT]
        print(f"*** TEST RUN: only {LIMIT} products. Set LIMIT = 0 for all. ***")

    print(f"To process: {len(todo)} products via {BACKEND}\n")

    with CACHE.open("a", encoding="utf-8") as fh:
        for i, row in enumerate(todo, 1):
            user_prompt = build_user_prompt(row)
            data = None

            for attempt in range(3):
                try:
                    candidate = parse_json(call(SYSTEM_PROMPT, user_prompt))
                except Exception as e:
                    print(f"  [retry {attempt + 1}] {row['Title'][:40]} -> {type(e).__name__}")
                    continue

                if has_cjk(candidate):
                    print(f"  [retry {attempt + 1}] CJK characters -> {row['Title'][:40]}")
                    user_prompt = (
                        build_user_prompt(row)
                        + "\n\nREMINDER: Thai and English characters ONLY. "
                        "No Chinese or Japanese characters anywhere."
                    )
                    continue

                data = candidate
                break

            if data is None:
                print(f"  [FAIL] {row['Title'][:45]} -> gave up after 3 tries")
                continue

            rec = {
                "Handle": row["Handle"],
                "Category": ", ".join(as_list(data.get("category"))),
                "Product_Type": snap_product_type(data.get("product_type")),
                "Best_For": ", ".join(as_list(data.get("best_for"))),
                "Org_Size": ", ".join(as_list(data.get("org_size"))),
                "Keywords": fix_spacing(
                    ", ".join(
                        as_list(data.get("keywords_en")) + as_list(data.get("keywords_th"))
                    )
                ),
                "Summary_EN": str(data.get("summary_en") or "").strip(),
                "Summary_TH": fix_spacing(str(data.get("summary_th") or "")),
                "Features": ", ".join(as_list(data.get("features"))),
            }

            fh.write(json.dumps(rec, ensure_ascii=False) + "\n")
            fh.flush()
            done[row["Handle"]] = rec

            if i % 10 == 0 or i == len(todo):
                print(f"  {i}/{len(todo)}  {row['Title'][:50]}")

    return done


# ---------------------------------------------------------------
# Pass 2 -- Alternatives from the REAL catalog only
# ---------------------------------------------------------------
def add_alternatives(df, top_n=3):
    """Same category, different vendor, closest keyword overlap.
    Guarantees every suggestion is a product mon.co.th actually sells."""

    def tokens(row):
        blob = f"{row.get('Category','')} {row.get('Product_Type','')} {row.get('Keywords','')}"
        return set(re.split(r"[,\s]+", str(blob).lower())) - {""}

    tok = {r["Handle"]: tokens(r) for _, r in df.iterrows()}
    cat = {r["Handle"]: {c.strip().lower() for c in str(r.get("Category", "")).split(",")}
           for _, r in df.iterrows()}

    alts = []
    for _, row in df.iterrows():
        h, me = row["Handle"], tok[row["Handle"]]
        scored = []
        for _, other in df.iterrows():
            oh = other["Handle"]
            if oh == h:
                continue
            if str(other.get("Vendor", "")).lower() == str(row.get("Vendor", "")).lower():
                continue
            if not (cat[h] & cat[oh]):
                continue
            overlap = len(me & tok[oh])
            if overlap >= 2:
                scored.append((overlap, other["Title"]))
        scored.sort(reverse=True)
        alts.append(", ".join(t for _, t in scored[:top_n]))
    return alts


def main():
    load_env()
    if BACKEND not in BACKENDS:
        sys.exit(f"Unknown BACKEND: {BACKEND}")

    df = pd.read_csv(SRC).fillna("")
    print(f"Loaded {len(df)} products from {SRC}")

    done = enrich(df)

    enriched = pd.DataFrame(done.values())
    out = df.merge(enriched, on="Handle", how="left").fillna("")
    out["Alternatives"] = add_alternatives(out)

    columns = [
        "Title", "Vendor", "Category", "Product_Type", "Best_For", "Org_Size",
        "Deployment", "Keywords", "Summary_TH", "Summary_EN", "Features",
        "Alternatives", "Price_Display", "Price_Min", "Price_Max",
        "Variants", "Description", "Tags", "URL", "Handle",
    ]
    out = out[[c for c in columns if c in out.columns]]
    out.to_csv(OUT, index=False, encoding="utf-8-sig")

    print(f"\nWrote {OUT}: {len(out)} rows")
    for c in ["Category", "Best_For", "Keywords", "Summary_TH", "Alternatives"]:
        if c in out.columns:
            filled = (out[c].astype(str).str.strip() != "").sum()
            print(f"  {c:14} filled: {filled}/{len(out)}")


if __name__ == "__main__":
    main()
